# Generated by Django 5.1.1 on 2024-09-16 16:25

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('scfhs_number', models.CharField(max_length=50)),
                ('participant_id', models.UUIDField(unique=True)),
                ('participant_type', models.CharField(choices=[('SP', 'Sponsor'), ('SR', 'Speaker'), ('DG', 'Delegate')], default='DG', max_length=2)),
            ],
        ),
    ]
