# Generated by Django 5.1.1 on 2024-09-23 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('phone', models.IntegerField(blank=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('scfhs_number', models.CharField(blank=True, max_length=50, null=True)),
                ('participant_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('inside', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('participant_type', models.CharField(choices=[('SP', 'Sponsor'), ('SR', 'Speaker'), ('DG', 'Delegate')], default='DG', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='QrCodeId',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('exit', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracking.participant')),
            ],
        ),
    ]
