# Generated by Django 5.1.1 on 2024-09-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0003_participant_inside_alter_participant_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
