# Generated by Django 5.1.1 on 2024-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0004_alter_participant_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
