# Generated by Django 5.1.1 on 2024-09-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0006_alter_participant_scfhs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
