# Generated by Django 5.1.1 on 2024-09-20 18:07

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0007_participant_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='participant',
            name='scfhs_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
